// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAf88Y54b1bnLL5MtDej6Thx2C5U12Pynk',
    appId: '1:127162471985:web:303b914b2a7d84f9456710',
    messagingSenderId: '127162471985',
    projectId: 'wander-oromia',
    authDomain: 'wander-oromia.firebaseapp.com',
    storageBucket: 'wander-oromia.firebasestorage.app',
    measurementId: 'G-WMJSF47T3F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVELML9OQITz3O8yzULBEaKuqIplcCId4',
    appId: '1:127162471985:android:7cdbc14a48c7435b456710',
    messagingSenderId: '127162471985',
    projectId: 'wander-oromia',
    storageBucket: 'wander-oromia.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtOA6AnpN18v4c7EcMPIjjyMys7UEsvts',
    appId: '1:127162471985:ios:61027e878a74dd15456710',
    messagingSenderId: '127162471985',
    projectId: 'wander-oromia',
    storageBucket: 'wander-oromia.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtOA6AnpN18v4c7EcMPIjjyMys7UEsvts',
    appId: '1:127162471985:ios:61027e878a74dd15456710',
    messagingSenderId: '127162471985',
    projectId: 'wander-oromia',
    storageBucket: 'wander-oromia.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAf88Y54b1bnLL5MtDej6Thx2C5U12Pynk',
    appId: '1:127162471985:web:0c986ba788765e12456710',
    messagingSenderId: '127162471985',
    projectId: 'wander-oromia',
    authDomain: 'wander-oromia.firebaseapp.com',
    storageBucket: 'wander-oromia.firebasestorage.app',
    measurementId: 'G-M6F9T46FN1',
  );
}
